[package]
name = "pixelquest"
version = "0.1.0"
edition = "2021"

[dependencies]
glium = "0.35"
device_query = "2.1.0"
cgmath = "0.18"
image = "0.24"
noise = "0.9.0"
rand = "0.8.5"
nalgebra = "0.33.0"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "blocks"
harness = false
